// 作品データをオブジェクトの配列で定義 (例: 9アイテムを左右対称に均等配置)
const worksData = [
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_1.png",
        title: "Character1",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_2.png",
        title: "Character2",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_3.png",
        title: "Character3",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_4.png",
        title: "Character4",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_5.png",
        title: "Character5",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_6.png",
        title: "Character6",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_7.png",
        title: "Character7",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_8.png",
        title: "Character8",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_1.png",
        title: "Character9",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_2.png",
        title: "Character10",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_3.png",
        title: "Character11",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_4.png",
        title: "Character12",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_5.png",
        title: "Character13",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_6.png",
        title: "Character14",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_7.png",
        title: "Character15",
        mask: "",
    },
    {
        r: 1, x: 0, y: 0,
        image_x: 0, image_y: 0,
        href: "",
        image: "images/character_8.png",
        title: "Character16",
        mask: "",
    },
];